// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXksbb7kv_BFLtCX_0_OToUbkpfguJI_4',
    appId: '1:813398755470:web:cf6aed17ac36e35788e1df',
    messagingSenderId: '813398755470',
    projectId: 'mymap-379607',
    authDomain: 'mymap-379607.firebaseapp.com',
    databaseURL: 'https://mymap-379607-default-rtdb.firebaseio.com',
    storageBucket: 'mymap-379607.appspot.com',
    measurementId: 'G-G4C6B15K8Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-iPrdYgl9Vl3ZHbOx_DDJpQYqbnfrSjM',
    appId: '1:813398755470:android:0a90ad57218c0c6888e1df',
    messagingSenderId: '813398755470',
    projectId: 'mymap-379607',
    databaseURL: 'https://mymap-379607-default-rtdb.firebaseio.com',
    storageBucket: 'mymap-379607.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDC5jGJnCzo8SjGNs9DQ8c1rA5i8EOK6T0',
    appId: '1:813398755470:ios:2b3c948637a0334088e1df',
    messagingSenderId: '813398755470',
    projectId: 'mymap-379607',
    databaseURL: 'https://mymap-379607-default-rtdb.firebaseio.com',
    storageBucket: 'mymap-379607.appspot.com',
    iosBundleId: 'com.example.chat',
  );
}
